// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCVg9mkJJLqA0s4dw6-TWhuWlEa6_MSh8',
    appId: '1:676972381757:web:532adade013021843c0c54',
    messagingSenderId: '676972381757',
    projectId: 'sajadah-app',
    authDomain: 'sajadah-app.firebaseapp.com',
    storageBucket: 'sajadah-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtTR8PFNFTyuwFivJKyWJOlWDwd-hDgg',
    appId: '1:676972381757:android:e274ae6748d95a4e3c0c54',
    messagingSenderId: '676972381757',
    projectId: 'sajadah-app',
    storageBucket: 'sajadah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nVxk8bKG2DxhppWmRDFsBLZZ1uSmn-s',
    appId: '1:676972381757:ios:ecd999151b7afb113c0c54',
    messagingSenderId: '676972381757',
    projectId: 'sajadah-app',
    storageBucket: 'sajadah-app.firebasestorage.app',
    iosBundleId: 'com.example.sajadah',
  );
}
